export const USER = [
    {
          "id": 1,
          "name": "Akash Kumar",
          "gender": "Male",
          "age": 23,
          "domain": "Full Stack Developer",
          "experience": 2,
          "skills": ["React.js", "Node.js", "MongoDB", "Express.js", "Tailwind CSS"],
          "salary": 75000,
          "company": "Tech Solutions Pvt Ltd",
          "location": "Remote"
        },
        {
          "id": 2,
          "name": "Priya Sharma",
          "gender": "Female",
          "age": 25,
          "domain": "Frontend Developer",
          "experience": 3,
          "skills": ["HTML", "CSS", "JavaScript", "React.js", "Redux"],
          "salary": 68000,
          "company": "Innovate Web Ltd",
          "location": "Bangalore"
        },
        {
          "id": 3,
          "name": "Rahul Verma",
          "gender": "Male",
          "age": 27,
          "domain": "Backend Developer",
          "experience": 5,
          "skills": ["Node.js", "Express.js", "MongoDB", "GraphQL"],
          "salary": 85000,
          "company": "DataSoft Inc",
          "location": "Mumbai"
        },
        {
          "id": 4,
          "name": "Neha Singh",
          "gender": "Female",
          "age": 24,
          "domain": "UI/UX Designer",
          "experience": 3,
          "skills": ["Figma", "Adobe XD", "CSS", "JavaScript"],
          "salary": 62000,
          "company": "DesignHub Ltd",
          "location": "Delhi"
        },
        {
          "id": 5,
          "name": "Amit Das",
          "gender": "Male",
          "age": 28,
          "domain": "DevOps Engineer",
          "experience": 6,
          "skills": ["Docker", "Kubernetes", "AWS", "Jenkins", "Terraform"],
          "salary": 95000,
          "company": "CloudOps Pvt Ltd",
          "location": "Hyderabad"
        },
        {
          "id": 6,
          "name": "Sneha Patil",
          "gender": "Female",
          "age": 26,
          "domain": "Data Scientist",
          "experience": 4,
          "skills": ["Python", "TensorFlow", "Pandas", "Machine Learning"],
          "salary": 90000,
          "company": "AI Analytics Ltd",
          "location": "Pune"
        },
        {
          "id": 7,
          "name": "Vikram Rao",
          "gender": "Male",
          "age": 30,
          "domain": "Cybersecurity Engineer",
          "experience": 7,
          "skills": ["Ethical Hacking", "Kali Linux", "Penetration Testing", "SIEM"],
          "salary": 110000,
          "company": "SecureNet Pvt Ltd",
          "location": "Chennai"
        },
        {
          "id": 8,
          "name": "Kavita Yadav",
          "gender": "Female",
          "age": 29,
          "domain": "Cloud Engineer",
          "experience": 6,
          "skills": ["AWS", "Azure", "Google Cloud", "Terraform"],
          "salary": 100000,
          "company": "CloudMasters Ltd",
          "location": "Bangalore"
        },
        {
          "id": 9,
          "name": "Rajesh Khanna",
          "gender": "Male",
          "age": 32,
          "domain": "AI/ML Engineer",
          "experience": 8,
          "skills": ["Python", "Deep Learning", "NLP", "Computer Vision"],
          "salary": 120000,
          "company": "AI Research Labs",
          "location": "Hyderabad"
        },
        {
          "id": 10,
          "name": "Sunita Agarwal",
          "gender": "Female",
          "age": 27,
          "domain": "Blockchain Developer",
          "experience": 5,
          "skills": ["Solidity", "Ethereum", "Web3.js", "Hyperledger"],
          "salary": 105000,
          "company": "Crypto Solutions Ltd",
          "location": "Mumbai"
        },
        {
            "id": 11,
            "name": "Ankit Mehta",
            "gender": "Male",
            "age": 26,
            "domain": "Software Engineer",
            "experience": 4,
            "skills": ["Java", "Spring Boot", "Microservices", "MySQL"],
            "salary": 82000,
            "company": "Tech Innovators",
            "location": "Delhi"
          },
          {
            "id": 12,
            "name": "Ritika Joshi",
            "gender": "Female",
            "age": 24,
            "domain": "Android Developer",
            "experience": 3,
            "skills": ["Kotlin", "Java", "Firebase", "Jetpack Compose"],
            "salary": 72000,
            "company": "Mobile First Pvt Ltd",
            "location": "Pune"
          },
          {
            "id": 13,
            "name": "Suresh Reddy",
            "gender": "Male",
            "age": 28,
            "domain": "Data Engineer",
            "experience": 5,
            "skills": ["Python", "Hadoop", "Spark", "Airflow"],
            "salary": 95000,
            "company": "Big Data Solutions",
            "location": "Hyderabad"
          },
          {
            "id": 14,
            "name": "Megha Kapoor",
            "gender": "Female",
            "age": 25,
            "domain": "Frontend Developer",
            "experience": 3,
            "skills": ["Vue.js", "Nuxt.js", "JavaScript", "CSS"],
            "salary": 68000,
            "company": "Frontend Masters",
            "location": "Bangalore"
          },
          {
            "id": 15,
            "name": "Yash Tiwari",
            "gender": "Male",
            "age": 27,
            "domain": "Embedded Systems Engineer",
            "experience": 6,
            "skills": ["C", "C++", "IoT", "Raspberry Pi"],
            "salary": 89000,
            "company": "SmartTech Pvt Ltd",
            "location": "Mumbai"
          },
          {
            "id": 16,
            "name": "Pooja Nair",
            "gender": "Female",
            "age": 29,
            "domain": "QA Engineer",
            "experience": 7,
            "skills": ["Selenium", "TestNG", "JIRA", "API Testing"],
            "salary": 85000,
            "company": "Quality Assurance Labs",
            "location": "Chennai"
          },
          {
            "id": 17,
            "name": "Arjun Malhotra",
            "gender": "Male",
            "age": 30,
            "domain": "Site Reliability Engineer",
            "experience": 8,
            "skills": ["Kubernetes", "Docker", "Prometheus", "CI/CD"],
            "salary": 115000,
            "company": "CloudTech Solutions",
            "location": "Bangalore"
          },
          {
            "id": 18,
            "name": "Shruti Deshmukh",
            "gender": "Female",
            "age": 26,
            "domain": "iOS Developer",
            "experience": 4,
            "skills": ["Swift", "Objective-C", "Core Data", "ARKit"],
            "salary": 90000,
            "company": "Apple Dev Studios",
            "location": "Pune"
          },
          {
            "id": 19,
            "name": "Rohan Gupta",
            "gender": "Male",
            "age": 25,
            "domain": "Game Developer",
            "experience": 3,
            "skills": ["Unity", "C#", "Unreal Engine", "Blender"],
            "salary": 75000,
            "company": "GamingWorld Pvt Ltd",
            "location": "Delhi"
          },
          {
            "id": 20,
            "name": "Ayesha Khan",
            "gender": "Female",
            "age": 28,
            "domain": "Robotics Engineer",
            "experience": 6,
            "skills": ["ROS", "Python", "Computer Vision", "AI"],
            "salary": 110000,
            "company": "RoboTech Labs",
            "location": "Hyderabad"
          },
            {
              "id": 21,
              "name": "Deepak Sinha",
              "gender": "Male",
              "age": 27,
              "domain": "Full Stack Developer",
              "experience": 4,
              "skills": ["React.js", "Node.js", "PostgreSQL", "GraphQL"],
              "salary": 88000,
              "company": "Techify Solutions",
              "location": "Bangalore"
            },
            {
              "id": 22,
              "name": "Ananya Gupta",
              "gender": "Female",
              "age": 24,
              "domain": "AI Engineer",
              "experience": 3,
              "skills": ["Python", "TensorFlow", "PyTorch", "Deep Learning"],
              "salary": 92000,
              "company": "AI Innovations Ltd",
              "location": "Hyderabad"
            },
            {
              "id": 23,
              "name": "Manish Reddy",
              "gender": "Male",
              "age": 29,
              "domain": "Cybersecurity Analyst",
              "experience": 6,
              "skills": ["Penetration Testing", "Malware Analysis", "SIEM", "Ethical Hacking"],
              "salary": 102000,
              "company": "SecureTech Pvt Ltd",
              "location": "Chennai"
            },
            {
              "id": 24,
              "name": "Ritu Verma",
              "gender": "Female",
              "age": 26,
              "domain": "Blockchain Developer",
              "experience": 4,
              "skills": ["Solidity", "Ethereum", "Smart Contracts", "Hyperledger"],
              "salary": 97000,
              "company": "CryptoTech Ltd",
              "location": "Mumbai"
            },
            {
              "id": 25,
              "name": "Akhil Sharma",
              "gender": "Male",
              "age": 28,
              "domain": "Cloud Engineer",
              "experience": 5,
              "skills": ["AWS", "Google Cloud", "Terraform", "Kubernetes"],
              "salary": 99000,
              "company": "CloudSphere Pvt Ltd",
              "location": "Delhi"
            },
            {
              "id": 26,
              "name": "Shraddha Patel",
              "gender": "Female",
              "age": 25,
              "domain": "Frontend Developer",
              "experience": 3,
              "skills": ["Vue.js", "React.js", "SCSS", "JavaScript"],
              "salary": 72000,
              "company": "Web Solutions Ltd",
              "location": "Pune"
            },
            {
              "id": 27,
              "name": "Sahil Khan",
              "gender": "Male",
              "age": 30,
              "domain": "DevOps Engineer",
              "experience": 7,
              "skills": ["Jenkins", "Docker", "CI/CD", "Terraform"],
              "salary": 105000,
              "company": "DevOps Masters",
              "location": "Bangalore"
            },
            {
              "id": 28,
              "name": "Neeraj Yadav",
              "gender": "Male",
              "age": 28,
              "domain": "Embedded Systems Engineer",
              "experience": 6,
              "skills": ["Embedded C", "IoT", "Raspberry Pi", "ARM Cortex"],
              "salary": 89000,
              "company": "SmartTech Pvt Ltd",
              "location": "Hyderabad"
            },
            {
              "id": 29,
              "name": "Aditi Nair",
              "gender": "Female",
              "age": 27,
              "domain": "iOS Developer",
              "experience": 5,
              "skills": ["Swift", "Objective-C", "Core Data", "SwiftUI"],
              "salary": 92000,
              "company": "Apple Dev Labs",
              "location": "Mumbai"
            },
            {
              "id": 30,
              "name": "Ramesh Patil",
              "gender": "Male",
              "age": 31,
              "domain": "Big Data Engineer",
              "experience": 8,
              "skills": ["Hadoop", "Spark", "Kafka", "Scala"],
              "salary": 115000,
              "company": "DataGenius Ltd",
              "location": "Chennai"
            },
            {
                  "id": 31,
                  "name": "Sanjay Rajput",
                  "gender": "Male",
                  "age": 26,
                  "domain": "Full Stack Developer",
                  "experience": 4,
                  "skills": ["React.js", "Node.js", "MongoDB", "Express.js"],
                  "salary": 85000,
                  "company": "NextGen Tech",
                  "location": "Delhi"
                },
                {
                  "id": 32,
                  "name": "Kiran Shah",
                  "gender": "Female",
                  "age": 24,
                  "domain": "Machine Learning Engineer",
                  "experience": 3,
                  "skills": ["Python", "TensorFlow", "NLP", "Deep Learning"],
                  "salary": 93000,
                  "company": "AI Revolution Ltd",
                  "location": "Hyderabad"
                },
                {
                  "id": 33,
                  "name": "Arvind Mehta",
                  "gender": "Male",
                  "age": 30,
                  "domain": "Cybersecurity Analyst",
                  "experience": 7,
                  "skills": ["Ethical Hacking", "SIEM", "Penetration Testing"],
                  "salary": 108000,
                  "company": "SecureZone Pvt Ltd",
                  "location": "Chennai"
                },
                {
                  "id": 34,
                  "name": "Roshni Desai",
                  "gender": "Female",
                  "age": 25,
                  "domain": "Blockchain Developer",
                  "experience": 3,
                  "skills": ["Solidity", "Ethereum", "Hyperledger"],
                  "salary": 95000,
                  "company": "CryptoWave Ltd",
                  "location": "Mumbai"
                },
                {
                  "id": 35,
                  "name": "Vivek Pandey",
                  "gender": "Male",
                  "age": 28,
                  "domain": "Cloud Engineer",
                  "experience": 6,
                  "skills": ["AWS", "Google Cloud", "Terraform"],
                  "salary": 98000,
                  "company": "CloudXperts Pvt Ltd",
                  "location": "Bangalore"
                },
                {
                  "id": 36,
                  "name": "Meera Iyer",
                  "gender": "Female",
                  "age": 27,
                  "domain": "Frontend Developer",
                  "experience": 5,
                  "skills": ["Angular", "TypeScript", "SCSS"],
                  "salary": 71000,
                  "company": "Web Innovators",
                  "location": "Pune"
                },
                {
                  "id": 37,
                  "name": "Zaid Khan",
                  "gender": "Male",
                  "age": 32,
                  "domain": "DevOps Engineer",
                  "experience": 8,
                  "skills": ["Jenkins", "Docker", "Kubernetes"],
                  "salary": 112000,
                  "company": "CloudOps Experts",
                  "location": "Hyderabad"
                },
                {
                  "id": 38,
                  "name": "Tanya Malhotra",
                  "gender": "Female",
                  "age": 26,
                  "domain": "Data Engineer",
                  "experience": 4,
                  "skills": ["Python", "Hadoop", "Kafka"],
                  "salary": 96000,
                  "company": "BigData Solutions",
                  "location": "Mumbai"
                },
                {
                  "id": 39,
                  "name": "Rajeev Sen",
                  "gender": "Male",
                  "age": 27,
                  "domain": "Backend Developer",
                  "experience": 6,
                  "skills": ["Django", "PostgreSQL", "GraphQL"],
                  "salary": 88000,
                  "company": "Backend Gurus",
                  "location": "Bangalore"
                },
                {
                  "id": 40,
                  "name": "Poonam Yadav",
                  "gender": "Female",
                  "age": 29,
                  "domain": "iOS Developer",
                  "experience": 5,
                  "skills": ["Swift", "Objective-C"],
                  "salary": 92000,
                  "company": "Apple DevTech",
                  "location": "Delhi"
                },
                {
                  "id": 41,
                  "name": "Nitin Tiwari",
                  "gender": "Male",
                  "age": 31,
                  "domain": "Big Data Engineer",
                  "experience": 9,
                  "skills": ["Spark", "Scala", "Hadoop"],
                  "salary": 118000,
                  "company": "DataGenius Ltd",
                  "location": "Chennai"
                },
                {
                  "id": 42,
                  "name": "Snehal Patil",
                  "gender": "Female",
                  "age": 28,
                  "domain": "AI/ML Engineer",
                  "experience": 6,
                  "skills": ["Deep Learning", "TensorFlow", "NLP"],
                  "salary": 110000,
                  "company": "AI Revolution Labs",
                  "location": "Hyderabad"
                },
                {
                  "id": 43,
                  "name": "Anurag Dixit",
                  "gender": "Male",
                  "age": 27,
                  "domain": "Game Developer",
                  "experience": 5,
                  "skills": ["Unity", "C#", "Blender"],
                  "salary": 86000,
                  "company": "Gaming Studios",
                  "location": "Pune"
                },
                {
                  "id": 44,
                  "name": "Radhika Jain",
                  "gender": "Female",
                  "age": 24,
                  "domain": "UI/UX Designer",
                  "experience": 3,
                  "skills": ["Adobe XD", "Figma", "CSS"],
                  "salary": 72000,
                  "company": "Creative UI Ltd",
                  "location": "Bangalore"
                },
                {
                  "id": 45,
                  "name": "Harshad Mehta",
                  "gender": "Male",
                  "age": 30,
                  "domain": "Robotics Engineer",
                  "experience": 7,
                  "skills": ["ROS", "Computer Vision"],
                  "salary": 115000,
                  "company": "RoboTech Labs",
                  "location": "Hyderabad"
                },
                {
                  "id": 46,
                  "name": "Sweta Dutta",
                  "gender": "Female",
                  "age": 26,
                  "domain": "Android Developer",
                  "experience": 4,
                  "skills": ["Kotlin", "Java"],
                  "salary": 89000,
                  "company": "Mobile Innovations",
                  "location": "Mumbai"
                },
                {
                  "id": 47,
                  "name": "Ankit Choudhary",
                  "gender": "Male",
                  "age": 29,
                  "domain": "Software Engineer",
                  "experience": 6,
                  "skills": ["Java", "Spring Boot", "Microservices"],
                  "salary": 99000,
                  "company": "Tech Leaders",
                  "location": "Delhi"
                },
                {
                  "id": 48,
                  "name": "Divya Narang",
                  "gender": "Female",
                  "age": 25,
                  "domain": "Data Scientist",
                  "experience": 4,
                  "skills": ["Python", "Pandas", "Machine Learning"],
                  "salary": 95000,
                  "company": "Data Insights Ltd",
                  "location": "Pune"
                },
                {
                  "id": 49,
                  "name": "Vikas Malhotra",
                  "gender": "Male",
                  "age": 30,
                  "domain": "Site Reliability Engineer",
                  "experience": 8,
                  "skills": ["Prometheus", "Grafana", "Kubernetes"],
                  "salary": 108000,
                  "company": "CloudOps Pvt Ltd",
                  "location": "Bangalore"
                },
                {
                  "id": 50,
                  "name": "Neelam Batra",
                  "gender": "Female",
                  "age": 27,
                  "domain": "AI Engineer",
                  "experience": 5,
                  "skills": ["TensorFlow", "Computer Vision", "NLP"],
                  "salary": 102000,
                  "company": "AI Solutions Ltd",
                  "location": "Hyderabad"
                },
              
              
          
  ]
  